### ISSUE TITLE
cloud-init does not work

### ISSUE THREAD

**Issue by erikschwalbe** [PlethoraOfHate/proxmox-deploy#2]
Creation of the vm does work, except of creating a harddrive.
But there is a error:
`Starting provisioning process
Creating Virtual Machine
Generating cloud-init seed files at /tmp/cloudinit-seed-isoUaDByA
Traceback (most recent call last):
  File "/usr/local/bin/proxmox-deploy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/proxmoxdeploy/cli.py", line 147, in main
    if os.path.exists(cloudinit_iso):
UnboundLocalError: local variable 'cloudinit_iso' referenced before assignment`

Proxmox-deploy Client: ubuntu 16.04 server
Poxmox Version: 4.4

Thanks for help

**Comment by joubertredrat** [comment]
same issue here

**Comment by openbsod** [comment]
Same here.
